# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: true

# Site meta
title: Jan's Cookbook
tagline: 'All the food'
description: 'Jan's Cookbook'
keywords: 'recipes'
url: https://darkoverlordofdata.github.io
baseurl: /summer
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: bruce davidson
  bio: Retired software engineer
  image: author
  url: https://github.com/darkoverlordofdata/summer
  email: darkoverlordofdata@gmail.com
  twitter: overlordofdata

social:
  twitter: https://twitter.com/overlordofdata
  instagram: https://instagram.com/darkoverlordofdata
  github: https://github.com/darkoverlordofdata/summer

version: 2.0.0

github:
  repo: https://github.com/darkoverlordofdata/summer
  
# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/darkoverlordofdata/summer
  Download: https://github.com/darkoverlordofdata/summer/archive/gh-pages.zip

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/

theme: jekyll-theme-minimal